#!/bin/bash -e
# Define some common paths
. faustpath

# Define compilation flags
. faustoptflags

# Helper file to build the 'help' option
. usage.sh

CXXFLAGS+=" -fPIC -shared"
CXXFLAGS+=" $MYGCCFLAGS"  # So that additional CXXFLAGS can be used
LIBADD+=" -pthread"

# The architecture file name
ARCHFILE=$FAUSTARCH/godot/godot.cpp

# Global variables
OPTIONS=""
FILES=""
UI=""
LIB_PREFIX=""
LIB_EXTENSION=""
EFFECT=false
GEFFECT=""
NVOICES=0

echoHelp()
{
    usage faust2godot "[options] [Faust options] <file.dsp>"
    echo "Compiles Faust programs to GDExtension usable in Godot game engine"
    option "-as-bus-effect" "force dsp to be compiled as Godot effect (even if it has no inputs)"
    option "Faust options"
    exit
}

if [ "$#" -eq 0 ]; then
    echo 'Please, provide a Faust file to process !'
    echo ''
    echoHelp
fi


#-------------------------------------------------------------------
# resolve lib decoration by platforms
#-------------------------------------------------------------------

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        LIB_PREFIX="lib"
        LIB_EXTENSION=".so"
elif [[ "$OSTYPE" == "darwin"* ]]; then
        LIB_PREFIX="lib"
        LIB_EXTENSION=".dylib"
elif [[ "$OSTYPE" == "msys" ]]; then
        LIB_PREFIX=""
        LIB_EXTENSION=".dll"
fi


#-------------------------------------------------------------------
# dispatch command arguments
#-------------------------------------------------------------------

while [ $1 ]
do
    p=$1

    if [ $p = "-help" ] || [ $p = "-h" ]; then
        echoHelp
    fi

    if [ $p = "-fx" ]; then
        OPTIONS="$OPTIONS $p"
        CXXFLAGS="$CXXFLAGS -I /usr/local/include/ap_fixed -DFIXED_POINT"
    elif [ $p = "-layout" ]; then
        UI="-DLAYOUT_UI"
    elif [ $p = "-effect" ]; then
          EFFECT=true
    elif [ $p = "-nvoices" ]; then
          shift
          NVOICES=$1
    elif [ $p = "-as-bus-effect" ]; then
          shift
          GEFFECT=$1
    elif [ ${p:0:1} = "-" ]; then
        OPTIONS="$OPTIONS $p"
    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
        FILES="$FILES $p"
    else
        OPTIONS="$OPTIONS $p"
    fi

shift

done

#-------------------------------------------------------------------
# compile the global effect file
#-------------------------------------------------------------------

if [ "$GEFFECT" != "" ]; then
  echo "compile the effect DSP to a .h using the minimal-effect architecture file"
  faust -i -cn effect -a minimal-effect.cpp "${GEFFECT}" -o "effect.h" || exit
fi

#-------------------------------------------------------------------
# compile the *.dsp files
#-------------------------------------------------------------------

for f in $FILES; do

    # compile the DSP to c++ using the architecture file
    echo "compile the DSP to c++ using the architecture file"
    faust -i -a $ARCHFILE $OPTIONS "$f" -o "${f%.dsp}.cpp"|| exit

    if [ "$EFFECT" = false ]; then
      # compile the DSP to json
      echo "compiling the dsp to Json"
      faust -json $OPTIONS "$f" -o "$f.json"|| exit

      INPUTS="$(cat $f.json | grep inputs | rev | cut -c 2)"

      if [ "$INPUTS" = 0 ]; then
        echo "Compiling dsp as generator"
        CXXFLAGS+=" -DGENERATOR_DSP=1"
      fi
    fi

    if [ "$NVOICES" -gt 0 ]; then
      echo "Compiling dsp as polyphonic"
      echo "Number of voices : ${NVOICES}"
      CXXFLAGS+=" -DPOLY -DNVOICES=${NVOICES}"
    fi

    # copy godot project template
    cp -r $FAUSTARCH/godot/template ./${f%.*}

    # compile c++ to binary
    echo "compile c++ to binary"
    (
        $CXX $CXXFLAGS "${f%.dsp}.cpp" $UI -o "./${f%.*}/bin/${LIB_PREFIX}faustdsp${LIB_EXTENSION}" ${LIBADD}
    ) > /dev/null || exit

    # remove temporary files
    rm -f "$f.json"
    rm -f "${f%.dsp}.cpp"
    rm -f "${GEFFECT%.dsp}.h"

    # collect binary file name for FaustWorks
    BINARIES="$BINARIES${f%.dsp};"

	# print sucess message in a h nice box
	printf "\n"
    msg="# DONE. Open the ${f%.*} directory inside Godot #"
    edge=$(echo "$msg" | sed 's/./#/g')
    echo "$edge"
    echo "$msg"
    echo "$edge"
	printf "\n"
done

echo $BINARIES